// The Fortune 500, as a checked-in list rather than ad-hoc SQL, matching the
// shape and reasoning of watchlist-seed.ts.
//
// Two caveats worth stating up front, because both affect what actually alerts:
//
//  1. This is the ~2024/25 ranking. Fortune republishes it annually and the
//     membership shifts by a few dozen names each year. It is a snapshot, not a
//     live feed, and nothing re-checks it.
//  2. Matching is by normalized employer name, so an entry only fires when a
//     source spells the employer the same way. `aliases` carry the spellings
//     these feeds actually use — the brand rather than the holding company
//     ("Google" for Alphabet), the common short form ("JPMorgan"), and the
//     ticker-ish abbreviations that show up in community repos. An entry with a
//     wrong name is not an error, it is silence, which is the failure mode to
//     watch for. `seed-watchlist.ts` prints what matched nothing.
//
// Most of these never post software internships to the sources we read. They
// cost one row each and catch the case where one eventually does.

import type { SeedCompany } from "./watchlist-seed.ts";

export const FORTUNE_500: SeedCompany[] = [
  // Retail, wholesale, and consumer
  { name: "Walmart", tier: "F500" },
  { name: "Amazon", tier: "F500", aliases: ["Amazon Web Services", "AWS"] },
  { name: "Costco", tier: "F500", aliases: ["Costco Wholesale"] },
  { name: "The Home Depot", tier: "F500", aliases: ["Home Depot"] },
  { name: "Target", tier: "F500", aliases: ["Target Corporation"] },
  { name: "Lowe's", tier: "F500", aliases: ["Lowes", "Lowe's Companies"] },
  { name: "TJX Companies", tier: "F500", aliases: ["TJX", "TJ Maxx"] },
  { name: "Dollar General", tier: "F500" },
  { name: "Dollar Tree", tier: "F500" },
  { name: "Best Buy", tier: "F500" },
  { name: "Publix Super Markets", tier: "F500", aliases: ["Publix"] },
  { name: "Kroger", tier: "F500", aliases: ["The Kroger Co."] },
  { name: "Albertsons", tier: "F500", aliases: ["Albertsons Companies"] },
  { name: "Sysco", tier: "F500" },
  { name: "US Foods", tier: "F500" },
  { name: "Performance Food Group", tier: "F500" },
  { name: "Nordstrom", tier: "F500" },
  { name: "Macy's", tier: "F500", aliases: ["Macys"] },
  { name: "Gap", tier: "F500", aliases: ["Gap Inc."] },
  { name: "Ross Stores", tier: "F500" },
  { name: "AutoZone", tier: "F500" },
  { name: "O'Reilly Automotive", tier: "F500", aliases: ["O'Reilly Auto Parts"] },
  { name: "Genuine Parts", tier: "F500" },
  { name: "Tractor Supply", tier: "F500" },
  { name: "Bath & Body Works", tier: "F500" },
  { name: "Foot Locker", tier: "F500" },
  { name: "Dick's Sporting Goods", tier: "F500", aliases: ["Dicks Sporting Goods"] },
  { name: "Williams-Sonoma", tier: "F500" },
  { name: "eBay", tier: "F500" },
  { name: "Etsy", tier: "F500" },
  { name: "Chewy", tier: "F500" },
  { name: "Wayfair", tier: "F500" },
  { name: "Qurate Retail", tier: "F500" },
  { name: "Rite Aid", tier: "F500" },
  { name: "Walgreens Boots Alliance", tier: "F500", aliases: ["Walgreens"] },

  // Healthcare, pharma, and insurance
  { name: "UnitedHealth Group", tier: "F500", aliases: ["UnitedHealth", "Optum"] },
  { name: "CVS Health", tier: "F500", aliases: ["CVS", "Aetna"] },
  { name: "McKesson", tier: "F500" },
  { name: "Cencora", tier: "F500", aliases: ["AmerisourceBergen"] },
  { name: "Cigna", tier: "F500", aliases: ["The Cigna Group", "Evernorth"] },
  { name: "Elevance Health", tier: "F500", aliases: ["Anthem"] },
  { name: "Centene", tier: "F500" },
  { name: "Humana", tier: "F500" },
  { name: "Molina Healthcare", tier: "F500" },
  { name: "HCA Healthcare", tier: "F500", aliases: ["HCA"] },
  { name: "Tenet Healthcare", tier: "F500" },
  { name: "Universal Health Services", tier: "F500" },
  { name: "Cardinal Health", tier: "F500" },
  { name: "Johnson & Johnson", tier: "F500", aliases: ["Johnson and Johnson", "J&J"] },
  { name: "Pfizer", tier: "F500" },
  { name: "Merck", tier: "F500", aliases: ["Merck & Co."] },
  { name: "AbbVie", tier: "F500" },
  { name: "Bristol-Myers Squibb", tier: "F500", aliases: ["Bristol Myers Squibb", "BMS"] },
  { name: "Eli Lilly", tier: "F500", aliases: ["Eli Lilly and Company", "Lilly"] },
  { name: "Amgen", tier: "F500" },
  { name: "Gilead Sciences", tier: "F500", aliases: ["Gilead"] },
  { name: "Moderna", tier: "F500" },
  { name: "Regeneron Pharmaceuticals", tier: "F500", aliases: ["Regeneron"] },
  { name: "Vertex Pharmaceuticals", tier: "F500", aliases: ["Vertex"] },
  { name: "Biogen", tier: "F500" },
  { name: "Viatris", tier: "F500" },
  { name: "Organon", tier: "F500" },
  { name: "Zoetis", tier: "F500" },
  { name: "Baxter International", tier: "F500", aliases: ["Baxter"] },
  { name: "Becton Dickinson", tier: "F500", aliases: ["BD"] },
  { name: "Boston Scientific", tier: "F500" },
  { name: "Stryker", tier: "F500" },
  { name: "Medtronic", tier: "F500" },
  { name: "Abbott Laboratories", tier: "F500", aliases: ["Abbott"] },
  { name: "Thermo Fisher Scientific", tier: "F500", aliases: ["Thermo Fisher"] },
  { name: "Danaher", tier: "F500" },
  { name: "Agilent Technologies", tier: "F500", aliases: ["Agilent"] },
  { name: "IQVIA", tier: "F500" },
  { name: "Labcorp", tier: "F500", aliases: ["LabCorp", "Laboratory Corporation of America"] },
  { name: "Quest Diagnostics", tier: "F500" },
  { name: "Henry Schein", tier: "F500" },
  { name: "DaVita", tier: "F500" },
  { name: "Encompass Health", tier: "F500" },

  // Technology, software, and semiconductors
  { name: "Apple", tier: "F500" },
  { name: "Alphabet", tier: "F500", aliases: ["Google"] },
  { name: "Microsoft", tier: "F500" },
  { name: "Meta Platforms", tier: "F500", aliases: ["Meta", "Facebook"] },
  { name: "Nvidia", tier: "F500", aliases: ["NVIDIA"] },
  { name: "Dell Technologies", tier: "F500", aliases: ["Dell"] },
  { name: "Intel", tier: "F500" },
  { name: "IBM", tier: "F500", aliases: ["International Business Machines"] },
  { name: "HP", tier: "F500", aliases: ["HP Inc.", "Hewlett-Packard"] },
  { name: "Hewlett Packard Enterprise", tier: "F500", aliases: ["HPE"] },
  { name: "Cisco Systems", tier: "F500", aliases: ["Cisco"] },
  { name: "Oracle", tier: "F500" },
  { name: "Salesforce", tier: "F500" },
  { name: "Broadcom", tier: "F500", aliases: ["VMware"] },
  { name: "Qualcomm", tier: "F500" },
  { name: "Advanced Micro Devices", tier: "F500", aliases: ["AMD"] },
  { name: "Texas Instruments", tier: "F500", aliases: ["TI"] },
  { name: "Micron Technology", tier: "F500", aliases: ["Micron"] },
  { name: "Applied Materials", tier: "F500" },
  { name: "Lam Research", tier: "F500" },
  { name: "KLA", tier: "F500", aliases: ["KLA-Tencor"] },
  { name: "Analog Devices", tier: "F500" },
  { name: "NXP Semiconductors", tier: "F500", aliases: ["NXP"] },
  { name: "ON Semiconductor", tier: "F500", aliases: ["onsemi"] },
  { name: "Marvell Technology", tier: "F500", aliases: ["Marvell"] },
  { name: "Western Digital", tier: "F500" },
  { name: "Seagate Technology", tier: "F500", aliases: ["Seagate"] },
  { name: "Corning", tier: "F500" },
  { name: "Jabil", tier: "F500" },
  { name: "Sanmina", tier: "F500" },
  { name: "Arrow Electronics", tier: "F500" },
  { name: "Avnet", tier: "F500" },
  { name: "TD Synnex", tier: "F500", aliases: ["Synnex"] },
  { name: "CDW", tier: "F500" },
  { name: "Insight Enterprises", tier: "F500" },
  { name: "Adobe", tier: "F500" },
  { name: "Intuit", tier: "F500" },
  { name: "ServiceNow", tier: "F500" },
  { name: "Workday", tier: "F500" },
  { name: "Autodesk", tier: "F500" },
  { name: "Synopsys", tier: "F500" },
  { name: "Cadence Design Systems", tier: "F500", aliases: ["Cadence"] },
  { name: "Palo Alto Networks", tier: "F500" },
  { name: "Fortinet", tier: "F500" },
  { name: "CrowdStrike", tier: "F500" },
  { name: "Palantir Technologies", tier: "F500", aliases: ["Palantir"] },
  { name: "Uber", tier: "F500", aliases: ["Uber Technologies"] },
  { name: "Lyft", tier: "F500" },
  { name: "DoorDash", tier: "F500" },
  { name: "Airbnb", tier: "F500" },
  { name: "Booking Holdings", tier: "F500", aliases: ["Booking.com", "Priceline"] },
  { name: "Expedia Group", tier: "F500", aliases: ["Expedia"] },
  { name: "Netflix", tier: "F500" },
  { name: "PayPal", tier: "F500", aliases: ["PayPal Holdings"] },
  { name: "Block", tier: "F500", aliases: ["Square", "Cash App"] },
  { name: "Coinbase", tier: "F500", aliases: ["Coinbase Global"] },
  { name: "Motorola Solutions", tier: "F500" },
  { name: "Keysight Technologies", tier: "F500", aliases: ["Keysight"] },
  { name: "Amphenol", tier: "F500" },
  { name: "TE Connectivity", tier: "F500" },
  { name: "Garmin", tier: "F500" },
  { name: "NetApp", tier: "F500" },
  { name: "Pure Storage", tier: "F500" },
  { name: "Nutanix", tier: "F500" },
  { name: "Snowflake", tier: "F500" },
  { name: "Datadog", tier: "F500" },
  { name: "Cloudflare", tier: "F500" },
  { name: "MongoDB", tier: "F500" },
  { name: "Twilio", tier: "F500" },
  { name: "Zoom", tier: "F500", aliases: ["Zoom Video Communications"] },
  { name: "Dropbox", tier: "F500" },
  { name: "DXC Technology", tier: "F500", aliases: ["DXC"] },
  { name: "Kyndryl", tier: "F500" },
  { name: "Leidos", tier: "F500" },
  { name: "Booz Allen Hamilton", tier: "F500", aliases: ["Booz Allen"] },
  { name: "CACI International", tier: "F500", aliases: ["CACI"] },
  { name: "SAIC", tier: "F500", aliases: ["Science Applications International"] },
  { name: "Cognizant", tier: "F500", aliases: ["Cognizant Technology Solutions"] },
  { name: "Accenture", tier: "F500" },
  { name: "Gartner", tier: "F500" },
  { name: "Concentrix", tier: "F500" },

  // Telecom and media
  { name: "AT&T", tier: "F500", aliases: ["ATT"] },
  { name: "Verizon", tier: "F500", aliases: ["Verizon Communications"] },
  { name: "T-Mobile", tier: "F500", aliases: ["T-Mobile US", "TMobile"] },
  { name: "Comcast", tier: "F500", aliases: ["NBCUniversal", "Sky"] },
  { name: "Charter Communications", tier: "F500", aliases: ["Spectrum"] },
  { name: "The Walt Disney Company", tier: "F500", aliases: ["Disney", "Walt Disney"] },
  { name: "Warner Bros. Discovery", tier: "F500", aliases: ["Warner Bros", "WBD"] },
  { name: "Paramount Global", tier: "F500", aliases: ["Paramount"] },
  { name: "Fox Corporation", tier: "F500", aliases: ["Fox"] },
  { name: "Liberty Media", tier: "F500" },
  { name: "Omnicom Group", tier: "F500", aliases: ["Omnicom"] },
  { name: "Interpublic Group", tier: "F500", aliases: ["IPG"] },
  { name: "News Corp", tier: "F500" },
  { name: "Electronic Arts", tier: "F500", aliases: ["EA"] },
  { name: "Take-Two Interactive", tier: "F500", aliases: ["Take Two", "Rockstar Games"] },
  { name: "Activision Blizzard", tier: "F500", aliases: ["Activision", "Blizzard"] },
  { name: "Roblox", tier: "F500" },
  { name: "Live Nation Entertainment", tier: "F500", aliases: ["Live Nation"] },
  { name: "Spotify", tier: "F500", aliases: ["Spotify Technology"] },
  { name: "DISH Network", tier: "F500", aliases: ["Dish"] },
  { name: "Lumen Technologies", tier: "F500", aliases: ["Lumen", "CenturyLink"] },
  { name: "Frontier Communications", tier: "F500" },

  // Banks, financial services, and payments
  { name: "JPMorgan Chase", tier: "F500", aliases: ["JPMorgan", "JP Morgan", "J.P. Morgan", "Chase"] },
  { name: "Bank of America", tier: "F500", aliases: ["BofA", "Merrill Lynch"] },
  { name: "Citigroup", tier: "F500", aliases: ["Citi"] },
  { name: "Wells Fargo", tier: "F500" },
  { name: "Goldman Sachs", tier: "F500", aliases: ["Goldman Sachs Group"] },
  { name: "Morgan Stanley", tier: "F500" },
  { name: "U.S. Bancorp", tier: "F500", aliases: ["US Bank", "US Bancorp"] },
  { name: "PNC Financial Services", tier: "F500", aliases: ["PNC"] },
  { name: "Truist Financial", tier: "F500", aliases: ["Truist"] },
  { name: "Capital One", tier: "F500", aliases: ["Capital One Financial"] },
  { name: "Charles Schwab", tier: "F500", aliases: ["Schwab"] },
  { name: "American Express", tier: "F500", aliases: ["Amex"] },
  { name: "Discover Financial Services", tier: "F500", aliases: ["Discover"] },
  { name: "Synchrony Financial", tier: "F500", aliases: ["Synchrony"] },
  { name: "Fifth Third Bancorp", tier: "F500", aliases: ["Fifth Third Bank"] },
  { name: "Citizens Financial Group", tier: "F500", aliases: ["Citizens Bank"] },
  { name: "KeyCorp", tier: "F500", aliases: ["KeyBank"] },
  { name: "M&T Bank", tier: "F500" },
  { name: "Huntington Bancshares", tier: "F500", aliases: ["Huntington Bank"] },
  { name: "Regions Financial", tier: "F500", aliases: ["Regions Bank"] },
  { name: "Ally Financial", tier: "F500", aliases: ["Ally"] },
  { name: "State Street", tier: "F500", aliases: ["State Street Corporation"] },
  { name: "BNY Mellon", tier: "F500", aliases: ["Bank of New York Mellon", "BNY"] },
  { name: "Northern Trust", tier: "F500" },
  { name: "BlackRock", tier: "F500" },
  { name: "Blackstone", tier: "F500" },
  { name: "KKR", tier: "F500" },
  { name: "Apollo Global Management", tier: "F500", aliases: ["Apollo"] },
  { name: "Carlyle Group", tier: "F500", aliases: ["Carlyle"] },
  { name: "Visa", tier: "F500" },
  { name: "Mastercard", tier: "F500" },
  { name: "Fiserv", tier: "F500" },
  { name: "Fidelity National Information Services", tier: "F500", aliases: ["FIS"] },
  { name: "Global Payments", tier: "F500" },
  { name: "Western Union", tier: "F500" },
  { name: "S&P Global", tier: "F500" },
  { name: "Moody's", tier: "F500", aliases: ["Moodys"] },
  { name: "MSCI", tier: "F500" },
  { name: "Nasdaq", tier: "F500" },
  { name: "Intercontinental Exchange", tier: "F500", aliases: ["ICE", "NYSE"] },
  { name: "CME Group", tier: "F500", aliases: ["CME"] },
  { name: "Cboe Global Markets", tier: "F500", aliases: ["Cboe"] },
  { name: "Robinhood Markets", tier: "F500", aliases: ["Robinhood"] },
  { name: "Berkshire Hathaway", tier: "F500" },
  { name: "Fannie Mae", tier: "F500" },
  { name: "Freddie Mac", tier: "F500" },
  { name: "Rocket Companies", tier: "F500", aliases: ["Rocket Mortgage", "Quicken Loans"] },
  { name: "SoFi Technologies", tier: "F500", aliases: ["SoFi"] },

  // Insurance
  { name: "Progressive", tier: "F500", aliases: ["Progressive Insurance"] },
  { name: "Allstate", tier: "F500", aliases: ["The Allstate Corporation"] },
  { name: "State Farm", tier: "F500" },
  { name: "Liberty Mutual", tier: "F500", aliases: ["Liberty Mutual Insurance"] },
  { name: "Travelers", tier: "F500", aliases: ["The Travelers Companies"] },
  { name: "Chubb", tier: "F500" },
  { name: "AIG", tier: "F500", aliases: ["American International Group"] },
  { name: "MetLife", tier: "F500" },
  { name: "Prudential Financial", tier: "F500", aliases: ["Prudential"] },
  { name: "Aflac", tier: "F500" },
  { name: "Nationwide", tier: "F500" },
  { name: "USAA", tier: "F500" },
  { name: "Massachusetts Mutual Life Insurance", tier: "F500", aliases: ["MassMutual"] },
  { name: "New York Life Insurance", tier: "F500", aliases: ["New York Life"] },
  { name: "Northwestern Mutual", tier: "F500" },
  { name: "Guardian Life", tier: "F500" },
  { name: "TIAA", tier: "F500" },
  { name: "Principal Financial Group", tier: "F500", aliases: ["Principal"] },
  { name: "Lincoln National", tier: "F500" },
  { name: "Hartford Financial Services", tier: "F500", aliases: ["The Hartford"] },
  { name: "Marsh & McLennan", tier: "F500", aliases: ["Marsh McLennan", "Mercer"] },
  { name: "Aon", tier: "F500" },
  { name: "Arthur J. Gallagher", tier: "F500", aliases: ["Gallagher"] },
  { name: "Cincinnati Financial", tier: "F500" },
  { name: "Markel", tier: "F500" },
  { name: "W. R. Berkley", tier: "F500", aliases: ["WR Berkley"] },
  { name: "Loews", tier: "F500" },
  { name: "Assurant", tier: "F500" },
  { name: "Unum", tier: "F500" },
  { name: "Equitable Holdings", tier: "F500", aliases: ["Equitable"] },

  // Energy, utilities, and chemicals
  { name: "Exxon Mobil", tier: "F500", aliases: ["ExxonMobil", "Exxon"] },
  { name: "Chevron", tier: "F500" },
  { name: "ConocoPhillips", tier: "F500" },
  { name: "Marathon Petroleum", tier: "F500" },
  { name: "Phillips 66", tier: "F500" },
  { name: "Valero Energy", tier: "F500", aliases: ["Valero"] },
  { name: "Occidental Petroleum", tier: "F500", aliases: ["Oxy"] },
  { name: "Hess", tier: "F500" },
  { name: "Devon Energy", tier: "F500" },
  { name: "EOG Resources", tier: "F500", aliases: ["EOG"] },
  { name: "Diamondback Energy", tier: "F500" },
  { name: "Halliburton", tier: "F500" },
  { name: "SLB", tier: "F500", aliases: ["Schlumberger"] },
  { name: "Baker Hughes", tier: "F500" },
  { name: "Kinder Morgan", tier: "F500" },
  { name: "Williams Companies", tier: "F500", aliases: ["Williams"] },
  { name: "Energy Transfer", tier: "F500" },
  { name: "Enterprise Products Partners", tier: "F500" },
  { name: "Plains All American Pipeline", tier: "F500", aliases: ["Plains All American"] },
  { name: "NextEra Energy", tier: "F500", aliases: ["NextEra", "Florida Power & Light"] },
  { name: "Duke Energy", tier: "F500" },
  { name: "Southern Company", tier: "F500", aliases: ["Southern Co"] },
  { name: "Dominion Energy", tier: "F500", aliases: ["Dominion"] },
  { name: "Exelon", tier: "F500" },
  { name: "American Electric Power", tier: "F500", aliases: ["AEP"] },
  { name: "Sempra", tier: "F500", aliases: ["Sempra Energy"] },
  { name: "Xcel Energy", tier: "F500" },
  { name: "Consolidated Edison", tier: "F500", aliases: ["Con Edison", "ConEd"] },
  { name: "PG&E", tier: "F500", aliases: ["Pacific Gas and Electric", "PGE"] },
  { name: "Edison International", tier: "F500", aliases: ["Southern California Edison"] },
  { name: "PSEG", tier: "F500", aliases: ["Public Service Enterprise Group"] },
  { name: "WEC Energy Group", tier: "F500", aliases: ["WEC Energy"] },
  { name: "DTE Energy", tier: "F500" },
  { name: "Entergy", tier: "F500" },
  { name: "FirstEnergy", tier: "F500" },
  { name: "Eversource Energy", tier: "F500", aliases: ["Eversource"] },
  { name: "CenterPoint Energy", tier: "F500", aliases: ["CenterPoint"] },
  { name: "Ameren", tier: "F500" },
  { name: "CMS Energy", tier: "F500" },
  { name: "AES", tier: "F500", aliases: ["The AES Corporation"] },
  { name: "NRG Energy", tier: "F500", aliases: ["NRG"] },
  { name: "Vistra", tier: "F500", aliases: ["Vistra Energy"] },
  { name: "Dow", tier: "F500", aliases: ["Dow Chemical"] },
  { name: "DuPont", tier: "F500", aliases: ["DuPont de Nemours"] },
  { name: "LyondellBasell", tier: "F500" },
  { name: "PPG Industries", tier: "F500", aliases: ["PPG"] },
  { name: "Sherwin-Williams", tier: "F500", aliases: ["Sherwin Williams"] },
  { name: "Ecolab", tier: "F500" },
  { name: "Air Products", tier: "F500", aliases: ["Air Products and Chemicals"] },
  { name: "Linde", tier: "F500" },
  { name: "Celanese", tier: "F500" },
  { name: "Eastman Chemical", tier: "F500", aliases: ["Eastman"] },
  { name: "Mosaic", tier: "F500", aliases: ["The Mosaic Company"] },
  { name: "Nucor", tier: "F500" },
  { name: "Steel Dynamics", tier: "F500" },
  { name: "Cleveland-Cliffs", tier: "F500", aliases: ["Cleveland Cliffs"] },
  { name: "Alcoa", tier: "F500" },
  { name: "Freeport-McMoRan", tier: "F500", aliases: ["Freeport McMoRan"] },
  { name: "International Paper", tier: "F500" },
  { name: "WestRock", tier: "F500" },
  { name: "Ball Corporation", tier: "F500", aliases: ["Ball"] },
  { name: "Sealed Air", tier: "F500" },
  { name: "Avery Dennison", tier: "F500" },

  // Aerospace, defense, industrials, and transport
  { name: "Boeing", tier: "F500", aliases: ["The Boeing Company"] },
  { name: "RTX", tier: "F500", aliases: ["Raytheon", "Raytheon Technologies", "Collins Aerospace", "Pratt & Whitney"] },
  { name: "Lockheed Martin", tier: "F500" },
  { name: "Northrop Grumman", tier: "F500" },
  { name: "General Dynamics", tier: "F500" },
  { name: "L3Harris Technologies", tier: "F500", aliases: ["L3Harris"] },
  { name: "HII", tier: "F500", aliases: ["Huntington Ingalls Industries", "Huntington Ingalls"] },
  { name: "Textron", tier: "F500" },
  { name: "TransDigm Group", tier: "F500", aliases: ["TransDigm"] },
  { name: "Howmet Aerospace", tier: "F500", aliases: ["Howmet"] },
  { name: "GE Aerospace", tier: "F500", aliases: ["General Electric", "GE"] },
  { name: "GE HealthCare", tier: "F500" },
  { name: "GE Vernova", tier: "F500" },
  { name: "Honeywell", tier: "F500", aliases: ["Honeywell International"] },
  { name: "3M", tier: "F500" },
  { name: "Emerson Electric", tier: "F500", aliases: ["Emerson"] },
  { name: "Eaton", tier: "F500", aliases: ["Eaton Corporation"] },
  { name: "Parker Hannifin", tier: "F500" },
  { name: "Illinois Tool Works", tier: "F500", aliases: ["ITW"] },
  { name: "Caterpillar", tier: "F500" },
  { name: "Deere & Company", tier: "F500", aliases: ["John Deere", "Deere"] },
  { name: "Cummins", tier: "F500" },
  { name: "Paccar", tier: "F500", aliases: ["PACCAR"] },
  { name: "Rockwell Automation", tier: "F500" },
  { name: "Dover", tier: "F500" },
  { name: "Stanley Black & Decker", tier: "F500", aliases: ["Stanley Black and Decker"] },
  { name: "Carrier Global", tier: "F500", aliases: ["Carrier"] },
  { name: "Trane Technologies", tier: "F500", aliases: ["Trane"] },
  { name: "Johnson Controls", tier: "F500" },
  { name: "Otis Worldwide", tier: "F500", aliases: ["Otis"] },
  { name: "Whirlpool", tier: "F500" },
  { name: "General Motors", tier: "F500", aliases: ["GM", "Cruise"] },
  { name: "Ford Motor", tier: "F500", aliases: ["Ford"] },
  { name: "Tesla", tier: "F500" },
  { name: "Rivian Automotive", tier: "F500", aliases: ["Rivian"] },
  { name: "Lucid Group", tier: "F500", aliases: ["Lucid Motors"] },
  { name: "Lear", tier: "F500", aliases: ["Lear Corporation"] },
  { name: "Aptiv", tier: "F500" },
  { name: "BorgWarner", tier: "F500" },
  { name: "Goodyear Tire & Rubber", tier: "F500", aliases: ["Goodyear"] },
  { name: "CarMax", tier: "F500" },
  { name: "Carvana", tier: "F500" },
  { name: "AutoNation", tier: "F500" },
  { name: "Penske Automotive Group", tier: "F500", aliases: ["Penske"] },
  { name: "Lithia Motors", tier: "F500", aliases: ["Lithia"] },
  { name: "United Parcel Service", tier: "F500", aliases: ["UPS"] },
  { name: "FedEx", tier: "F500" },
  { name: "Union Pacific", tier: "F500" },
  { name: "CSX", tier: "F500" },
  { name: "Norfolk Southern", tier: "F500" },
  { name: "Delta Air Lines", tier: "F500", aliases: ["Delta"] },
  { name: "United Airlines", tier: "F500", aliases: ["United Airlines Holdings"] },
  { name: "American Airlines", tier: "F500", aliases: ["American Airlines Group"] },
  { name: "Southwest Airlines", tier: "F500", aliases: ["Southwest"] },
  { name: "Alaska Air Group", tier: "F500", aliases: ["Alaska Airlines"] },
  { name: "JetBlue Airways", tier: "F500", aliases: ["JetBlue"] },
  { name: "XPO", tier: "F500" },
  { name: "C.H. Robinson", tier: "F500", aliases: ["CH Robinson"] },
  { name: "Expeditors International", tier: "F500", aliases: ["Expeditors"] },
  { name: "J.B. Hunt Transport Services", tier: "F500", aliases: ["JB Hunt"] },
  { name: "Old Dominion Freight Line", tier: "F500", aliases: ["Old Dominion"] },
  { name: "Uber Freight", tier: "F500" },
  { name: "Waste Management", tier: "F500", aliases: ["WM"] },
  { name: "Republic Services", tier: "F500" },

  // Food, beverage, household, and apparel
  { name: "PepsiCo", tier: "F500", aliases: ["Pepsi", "Frito-Lay"] },
  { name: "The Coca-Cola Company", tier: "F500", aliases: ["Coca-Cola", "Coke"] },
  { name: "Procter & Gamble", tier: "F500", aliases: ["P&G", "Procter and Gamble"] },
  { name: "Mondelez International", tier: "F500", aliases: ["Mondelez"] },
  { name: "General Mills", tier: "F500" },
  { name: "Kellanova", tier: "F500", aliases: ["Kellogg", "Kellogg's"] },
  { name: "Kraft Heinz", tier: "F500", aliases: ["The Kraft Heinz Company"] },
  { name: "Conagra Brands", tier: "F500", aliases: ["Conagra"] },
  { name: "Hormel Foods", tier: "F500", aliases: ["Hormel"] },
  { name: "Tyson Foods", tier: "F500", aliases: ["Tyson"] },
  { name: "Archer Daniels Midland", tier: "F500", aliases: ["ADM"] },
  { name: "Bunge Global", tier: "F500", aliases: ["Bunge"] },
  { name: "Cargill", tier: "F500" },
  { name: "The Hershey Company", tier: "F500", aliases: ["Hershey"] },
  { name: "J.M. Smucker", tier: "F500", aliases: ["Smucker"] },
  { name: "Campbell Soup", tier: "F500", aliases: ["Campbell's"] },
  { name: "McCormick", tier: "F500" },
  { name: "Keurig Dr Pepper", tier: "F500", aliases: ["Dr Pepper"] },
  { name: "Monster Beverage", tier: "F500", aliases: ["Monster Energy"] },
  { name: "Constellation Brands", tier: "F500" },
  { name: "Molson Coors", tier: "F500" },
  { name: "Altria Group", tier: "F500", aliases: ["Altria"] },
  { name: "Philip Morris International", tier: "F500", aliases: ["Philip Morris"] },
  { name: "Colgate-Palmolive", tier: "F500", aliases: ["Colgate"] },
  { name: "Kimberly-Clark", tier: "F500", aliases: ["Kimberly Clark"] },
  { name: "Estée Lauder", tier: "F500", aliases: ["Estee Lauder", "The Estée Lauder Companies"] },
  { name: "Church & Dwight", tier: "F500", aliases: ["Church and Dwight"] },
  { name: "Clorox", tier: "F500", aliases: ["The Clorox Company"] },
  { name: "Nike", tier: "F500", aliases: ["NIKE"] },
  { name: "VF Corporation", tier: "F500", aliases: ["VF Corp"] },
  { name: "Ralph Lauren", tier: "F500" },
  { name: "PVH", tier: "F500", aliases: ["PVH Corp", "Calvin Klein", "Tommy Hilfiger"] },
  { name: "Tapestry", tier: "F500", aliases: ["Coach"] },
  { name: "Levi Strauss", tier: "F500", aliases: ["Levi's"] },
  { name: "Skechers", tier: "F500" },
  { name: "Deckers Brands", tier: "F500", aliases: ["Deckers Outdoor"] },
  { name: "Lululemon Athletica", tier: "F500", aliases: ["Lululemon"] },
  { name: "McDonald's", tier: "F500", aliases: ["McDonalds"] },
  { name: "Starbucks", tier: "F500" },
  { name: "Chipotle Mexican Grill", tier: "F500", aliases: ["Chipotle"] },
  { name: "Yum! Brands", tier: "F500", aliases: ["Yum Brands", "Taco Bell", "KFC"] },
  { name: "Restaurant Brands International", tier: "F500", aliases: ["Burger King"] },
  { name: "Darden Restaurants", tier: "F500", aliases: ["Darden"] },
  { name: "Domino's Pizza", tier: "F500", aliases: ["Dominos"] },
  { name: "Aramark", tier: "F500" },
  { name: "Marriott International", tier: "F500", aliases: ["Marriott"] },
  { name: "Hilton Worldwide", tier: "F500", aliases: ["Hilton"] },
  { name: "Hyatt Hotels", tier: "F500", aliases: ["Hyatt"] },
  { name: "MGM Resorts International", tier: "F500", aliases: ["MGM Resorts"] },
  { name: "Caesars Entertainment", tier: "F500", aliases: ["Caesars"] },
  { name: "Las Vegas Sands", tier: "F500" },
  { name: "Royal Caribbean Group", tier: "F500", aliases: ["Royal Caribbean"] },
  { name: "Carnival", tier: "F500", aliases: ["Carnival Corporation"] },
  { name: "Norwegian Cruise Line Holdings", tier: "F500", aliases: ["Norwegian Cruise Line"] },

  // Real estate, construction, and services
  { name: "CBRE Group", tier: "F500", aliases: ["CBRE"] },
  { name: "Jones Lang LaSalle", tier: "F500", aliases: ["JLL"] },
  { name: "Prologis", tier: "F500" },
  { name: "American Tower", tier: "F500" },
  { name: "Equinix", tier: "F500" },
  { name: "Crown Castle", tier: "F500" },
  { name: "Digital Realty", tier: "F500", aliases: ["Digital Realty Trust"] },
  { name: "Simon Property Group", tier: "F500", aliases: ["Simon Property"] },
  { name: "Welltower", tier: "F500" },
  { name: "D.R. Horton", tier: "F500", aliases: ["DR Horton"] },
  { name: "Lennar", tier: "F500" },
  { name: "PulteGroup", tier: "F500", aliases: ["Pulte Homes"] },
  { name: "NVR", tier: "F500" },
  { name: "Builders FirstSource", tier: "F500" },
  { name: "Fluor", tier: "F500", aliases: ["Fluor Corporation"] },
  { name: "AECOM", tier: "F500" },
  { name: "Jacobs Solutions", tier: "F500", aliases: ["Jacobs", "Jacobs Engineering"] },
  { name: "Quanta Services", tier: "F500", aliases: ["Quanta"] },
  { name: "EMCOR Group", tier: "F500", aliases: ["EMCOR"] },
  { name: "MasTec", tier: "F500" },
  { name: "Vulcan Materials", tier: "F500" },
  { name: "Martin Marietta Materials", tier: "F500", aliases: ["Martin Marietta"] },
  { name: "Cintas", tier: "F500" },
  { name: "Automatic Data Processing", tier: "F500", aliases: ["ADP"] },
  { name: "Paychex", tier: "F500" },
  { name: "Robert Half", tier: "F500" },
  { name: "ManpowerGroup", tier: "F500", aliases: ["Manpower"] },
  { name: "Equifax", tier: "F500" },
  { name: "TransUnion", tier: "F500" },
  { name: "Experian", tier: "F500" },
  { name: "Thomson Reuters", tier: "F500" },
  { name: "Verisk Analytics", tier: "F500", aliases: ["Verisk"] },
  { name: "Nielsen", tier: "F500" },
  { name: "United Rentals", tier: "F500" },
  { name: "W.W. Grainger", tier: "F500", aliases: ["Grainger"] },
  { name: "Fastenal", tier: "F500" },
  { name: "Ferguson", tier: "F500" },
  { name: "WESCO International", tier: "F500", aliases: ["Wesco"] },
];
